"""
pvp/cards.py
All 300 elemental action cards: 100 Fire, 100 Ice, 100 Lightning.
Tune balance here — nowhere else needs to change for stat adjustments.
"""

# ── Effect constructors ────────────────────────────────────────────────────────
def _d(v):        return {"type": "damage",           "value": v}
def _h(v):        return {"type": "heal",              "value": v}
def _s(v):        return {"type": "shield",            "value": v}
def _b(v, d=2):   return {"type": "burn",              "value": v, "duration": d}
def _fr(d=1):     return {"type": "freeze",            "duration": d}
def _st(v):       return {"type": "stun",              "value": v}
def _dr(v):       return {"type": "draw_cards",        "value": v}
def _do(v):       return {"type": "discard_opponent",  "value": v}
def _en(v):       return {"type": "energize",          "value": v}
def _dn(v):       return {"type": "drain",             "value": v}

def _card(cid, name, element, cost, effects, desc, flavor=""):
    return {
        "id":       cid,
        "name":     name,
        "element":  element,
        "cost":     cost,
        "effects":  effects,
        "description": desc,
        "flavor":   flavor,
    }

F = "fire"
I = "ice"
L = "lightning"

# ══════════════════════════════════════════════════════════════════════════════
# FIRE CARDS (100)  — aggressive, burn, drain
# ══════════════════════════════════════════════════════════════════════════════
FIRE_CARDS = [
    # ── 1-cost (35) ───────────────────────────────────────────────────────────
    _card("F001","Ember Strike",     F,1,[_d(2)],              "Deal 2 damage."),
    _card("F002","Spark Throw",      F,1,[_d(2)],              "Deal 2 damage."),
    _card("F003","Flame Flick",      F,1,[_d(1),_b(1,1)],     "Deal 1 dmg. Burn 1 for 1 turn."),
    _card("F004","Heat Wave",        F,1,[_d(2)],              "Deal 2 damage."),
    _card("F005","Cinder Toss",      F,1,[_d(2)],              "Deal 2 damage."),
    _card("F006","Smolder",          F,1,[_b(2,2)],            "Burn opponent 2/turn for 2 turns."),
    _card("F007","Ignite",           F,1,[_d(1),_b(1,2)],     "Deal 1 dmg. Burn 1 for 2 turns."),
    _card("F008","Flash Fire",       F,1,[_d(2)],              "Deal 2 damage."),
    _card("F009","Blaze Step",       F,1,[_d(2)],              "Deal 2 damage."),
    _card("F010","Fire Bolt",        F,1,[_d(2)],              "Deal 2 damage."),
    _card("F011","Hot Coal",         F,1,[_d(1),_b(1,1)],     "Deal 1 dmg. Burn 1 for 1 turn."),
    _card("F012","Kindle",           F,1,[_d(1),_dr(1)],      "Deal 1 dmg. Draw 1 card."),
    _card("F013","Ash Shower",       F,1,[_do(1)],             "Opponent discards 1 card."),
    _card("F014","Pyro Pulse",       F,1,[_d(2)],              "Deal 2 damage."),
    _card("F015","Flame Tongue",     F,1,[_d(2)],              "Deal 2 damage."),
    _card("F016","Sear",             F,1,[_d(1),_b(1,3)],     "Deal 1 dmg. Burn 1 for 3 turns."),
    _card("F017","Flare",            F,1,[_d(2)],              "Deal 2 damage."),
    _card("F018","Smoke Screen",     F,1,[_st(1)],             "Opponent loses 1 mana next turn."),
    _card("F019","Magma Drop",       F,1,[_d(2)],              "Deal 2 damage."),
    _card("F020","Scorch Mark",      F,1,[_d(1),_b(2,1)],     "Deal 1 dmg. Burn 2 for 1 turn."),
    _card("F021","Fire Tap",         F,1,[_d(1)],              "Deal 1 damage."),
    _card("F022","Pyre Touch",       F,1,[_d(2)],              "Deal 2 damage."),
    _card("F023","Heat Pulse",       F,1,[_d(2)],              "Deal 2 damage."),
    _card("F024","Char",             F,1,[_d(1)],              "Deal 1 damage."),
    _card("F025","Burning Gaze",     F,1,[_d(1),_b(1,1)],     "Deal 1 dmg. Burn 1 for 1 turn."),
    _card("F026","Spark Dance",      F,1,[_d(2)],              "Deal 2 damage."),
    _card("F027","Infernal Tick",    F,1,[_b(1,3)],            "Burn opponent 1/turn for 3 turns."),
    _card("F028","Smoldering Gaze",  F,1,[_d(2)],              "Deal 2 damage."),
    _card("F029","Lava Drip",        F,1,[_d(1),_b(1,2)],     "Deal 1 dmg. Burn 1 for 2 turns."),
    _card("F030","Fire Mist",        F,1,[_d(2)],              "Deal 2 damage."),
    _card("F031","Torch Throw",      F,1,[_d(2)],              "Deal 2 damage."),
    _card("F032","Flame Spit",       F,1,[_d(2)],              "Deal 2 damage."),
    _card("F033","Hot Streak",       F,1,[_d(2)],              "Deal 2 damage."),
    _card("F034","Burning Zeal",     F,1,[_d(1),_dr(1)],      "Deal 1 dmg. Draw 1 card."),
    _card("F035","Pyro Spark",       F,1,[_d(2)],              "Deal 2 damage."),
    # ── 2-cost (35) ───────────────────────────────────────────────────────────
    _card("F036","Fireball",         F,2,[_d(4)],              "Deal 4 damage."),
    _card("F037","Flame Surge",      F,2,[_d(3),_b(1,1)],     "Deal 3 dmg. Burn 1 for 1 turn."),
    _card("F038","Magma Burst",      F,2,[_d(4)],              "Deal 4 damage."),
    _card("F039","Fire Slash",       F,2,[_d(3)],              "Deal 3 damage."),
    _card("F040","Burning Fist",     F,2,[_d(3),_b(1,1)],     "Deal 3 dmg. Burn 1 for 1 turn."),
    _card("F041","Scorching Blow",   F,2,[_d(4)],              "Deal 4 damage."),
    _card("F042","Lava Ball",        F,2,[_d(3),_b(1,2)],     "Deal 3 dmg. Burn 1 for 2 turns."),
    _card("F043","Inferno Strike",   F,2,[_d(4)],              "Deal 4 damage."),
    _card("F044","Flame Dance",      F,2,[_d(3),_h(1)],       "Deal 3 dmg. Heal 1."),
    _card("F045","Dragon's Breath",  F,2,[_d(3),_b(2,1)],     "Deal 3 dmg. Burn 2 for 1 turn."),
    _card("F046","Pyroclast",        F,2,[_d(4)],              "Deal 4 damage."),
    _card("F047","Firestorm",        F,2,[_d(3),_dr(1)],      "Deal 3 dmg. Draw 1 card."),
    _card("F048","Magma Punch",      F,2,[_d(3),_b(1,1)],     "Deal 3 dmg. Burn 1 for 1 turn."),
    _card("F049","Blazing Cut",      F,2,[_d(4)],              "Deal 4 damage."),
    _card("F050","Ember Wave",       F,2,[_d(3),_do(1)],      "Deal 3 dmg. Opponent discards 1."),
    _card("F051","Fire Fang",        F,2,[_d(3)],              "Deal 3 damage."),
    _card("F052","Scorch Beam",      F,2,[_d(4)],              "Deal 4 damage."),
    _card("F053","Heat Cannon",      F,2,[_d(4)],              "Deal 4 damage."),
    _card("F054","Flame Whip",       F,2,[_d(3),_b(1,2)],     "Deal 3 dmg. Burn 1 for 2 turns."),
    _card("F055","Infernal Bolt",    F,2,[_d(4)],              "Deal 4 damage."),
    _card("F056","Burning Strike",   F,2,[_d(3)],              "Deal 3 damage."),
    _card("F057","Pyro Burst",       F,2,[_d(3),_b(2,1)],     "Deal 3 dmg. Burn 2 for 1 turn."),
    _card("F058","Lava Splash",      F,2,[_d(4)],              "Deal 4 damage."),
    _card("F059","Fire Arrow",       F,2,[_d(3)],              "Deal 3 damage."),
    _card("F060","Scorching Wave",   F,2,[_d(3),_st(1)],      "Deal 3 dmg. Opp loses 1 mana next turn."),
    _card("F061","Magma Spike",      F,2,[_d(3),_b(1,1)],     "Deal 3 dmg. Burn 1 for 1 turn."),
    _card("F062","Flame Kick",       F,2,[_d(3)],              "Deal 3 damage."),
    _card("F063","Burning Chain",    F,2,[_d(3),_dr(1)],      "Deal 3 dmg. Draw 1 card."),
    _card("F064","Fire Drain",       F,2,[_dn(3)],             "Drain 3: deal 3 dmg, heal 1."),
    _card("F065","Pyroblast",        F,2,[_d(4)],              "Deal 4 damage."),
    _card("F066","Incendiary Round", F,2,[_d(3),_b(1,2)],     "Deal 3 dmg. Burn 1 for 2 turns."),
    _card("F067","Heat Blast",       F,2,[_d(4)],              "Deal 4 damage."),
    _card("F068","Volcanic Spit",    F,2,[_d(3)],              "Deal 3 damage."),
    _card("F069","Flame Geyser",     F,2,[_d(4)],              "Deal 4 damage."),
    _card("F070","Cinder Storm",     F,2,[_d(3),_b(1,1)],     "Deal 3 dmg. Burn 1 for 1 turn."),
    # ── 3-cost (20) ───────────────────────────────────────────────────────────
    _card("F071","Great Fireball",   F,3,[_d(6)],              "Deal 6 damage."),
    _card("F072","Inferno Wave",     F,3,[_d(5),_b(2,2)],     "Deal 5 dmg. Burn 2 for 2 turns."),
    _card("F073","Dragon Roar",      F,3,[_d(6),_b(1,2)],     "Deal 6 dmg. Burn 1 for 2 turns."),
    _card("F074","Volcanic Eruption",F,3,[_d(5),_b(3,1)],     "Deal 5 dmg. Burn 3 for 1 turn."),
    _card("F075","Magma Surge",      F,3,[_d(5),_h(2)],       "Deal 5 dmg. Heal 2."),
    _card("F076","Phoenix Strike",   F,3,[_d(6),_h(1)],       "Deal 6 dmg. Heal 1."),
    _card("F077","Flame Tornado",    F,3,[_d(5),_b(2,1)],     "Deal 5 dmg. Burn 2 for 1 turn."),
    _card("F078","Wildfire",         F,3,[_d(5),_dr(2)],      "Deal 5 dmg. Draw 2 cards."),
    _card("F079","Solar Flare",      F,3,[_d(6)],              "Deal 6 damage."),
    _card("F080","Molten Rage",      F,3,[_d(5),_b(1,3)],     "Deal 5 dmg. Burn 1 for 3 turns."),
    _card("F081","Infernal Rain",    F,3,[_d(5),_b(2,2)],     "Deal 5 dmg. Burn 2 for 2 turns."),
    _card("F082","Blazing Tempest",  F,3,[_d(6)],              "Deal 6 damage."),
    _card("F083","Pyroclastic Flow", F,3,[_d(5),_st(2)],      "Deal 5 dmg. Opp loses 2 mana next turn."),
    _card("F084","Fire Convergence", F,3,[_d(5),_b(3,1)],     "Deal 5 dmg. Burn 3 for 1 turn."),
    _card("F085","Ember Tsunami",    F,3,[_d(6),_b(1,1)],     "Deal 6 dmg. Burn 1 for 1 turn."),
    _card("F086","Magma Overlord",   F,3,[_d(5),_h(2)],       "Deal 5 dmg. Heal 2."),
    _card("F087","Dragon's Fury",    F,3,[_d(6),_b(1,2)],     "Deal 6 dmg. Burn 1 for 2 turns."),
    _card("F088","Immolation",       F,3,[_d(5),_b(2,3)],     "Deal 5 dmg. Burn 2 for 3 turns."),
    _card("F089","Flame Emperor",    F,3,[_d(6),_dr(1)],      "Deal 6 dmg. Draw 1 card."),
    _card("F090","Hellfire Surge",   F,3,[_d(6),_b(2,1)],     "Deal 6 dmg. Burn 2 for 1 turn."),
    # ── 4-cost (7) ────────────────────────────────────────────────────────────
    _card("F091","Cataclysm Flame",  F,4,[_d(8)],              "Deal 8 damage."),
    _card("F092","Volcanic God",     F,4,[_d(7),_b(3,2)],     "Deal 7 dmg. Burn 3 for 2 turns."),
    _card("F093","Dragon King's Breath",F,4,[_d(8),_b(2,2)],  "Deal 8 dmg. Burn 2 for 2 turns."),
    _card("F094","Hellstorm",        F,4,[_dn(7)],             "Drain 7: deal 7 dmg, heal 3."),
    _card("F095","Phoenix Rebirth",  F,4,[_d(4),_h(5)],       "Deal 4 dmg. Heal 5 HP."),
    _card("F096","Solar Prominence", F,4,[_d(8)],              "Deal 8 damage."),
    _card("F097","Eternal Flame",    F,4,[_d(7),_b(1,5)],     "Deal 7 dmg. Burn 1 for 5 turns."),
    # ── 5-cost (3) ────────────────────────────────────────────────────────────
    _card("F098","Armageddon",       F,5,[_d(10)],             "Deal 10 damage."),
    _card("F099","Sun Eater",        F,5,[_d(9),_b(3,3)],     "Deal 9 dmg. Burn 3 for 3 turns."),
    _card("F100","Primordial Fire",  F,5,[_d(9),_h(3),_b(2,2)],"Deal 9 dmg. Heal 3. Burn 2 for 2 turns."),
]

# ══════════════════════════════════════════════════════════════════════════════
# ICE CARDS (100) — control, shield, freeze, slow
# ══════════════════════════════════════════════════════════════════════════════
ICE_CARDS = [
    # ── 1-cost (35) ───────────────────────────────────────────────────────────
    _card("I001","Ice Shard",        I,1,[_d(2)],              "Deal 2 damage."),
    _card("I002","Frost Bite",       I,1,[_d(1),_s(1)],       "Deal 1 dmg. Gain 1 shield."),
    _card("I003","Chill Touch",      I,1,[_d(2)],              "Deal 2 damage."),
    _card("I004","Snow Flurry",      I,1,[_d(1),_st(1)],      "Deal 1 dmg. Opp loses 1 mana next turn."),
    _card("I005","Cold Snap",        I,1,[_d(2)],              "Deal 2 damage."),
    _card("I006","Ice Dart",         I,1,[_d(2)],              "Deal 2 damage."),
    _card("I007","Frost Pulse",      I,1,[_d(1),_s(2)],       "Deal 1 dmg. Gain 2 shield."),
    _card("I008","Glacial Chip",     I,1,[_d(2)],              "Deal 2 damage."),
    _card("I009","Shiver",           I,1,[_st(1)],             "Opponent loses 1 mana next turn."),
    _card("I010","Frost Bolt",       I,1,[_d(2)],              "Deal 2 damage."),
    _card("I011","Icy Veil",         I,1,[_s(3)],              "Gain 3 shield."),
    _card("I012","Snowfall",         I,1,[_d(1),_dr(1)],      "Deal 1 dmg. Draw 1 card."),
    _card("I013","Cold Shoulder",    I,1,[_d(1),_s(1)],       "Deal 1 dmg. Gain 1 shield."),
    _card("I014","Ice Pick",         I,1,[_d(2)],              "Deal 2 damage."),
    _card("I015","Chill Mist",       I,1,[_d(1),_st(1)],      "Deal 1 dmg. Opp loses 1 mana."),
    _card("I016","Frost Dust",       I,1,[_d(1),_s(2)],       "Deal 1 dmg. Gain 2 shield."),
    _card("I017","Glacial Touch",    I,1,[_d(2)],              "Deal 2 damage."),
    _card("I018","Freeze Spark",     I,1,[_d(1)],              "Deal 1 damage."),
    _card("I019","Ice Film",         I,1,[_s(3)],              "Gain 3 shield."),
    _card("I020","Cold Wave",        I,1,[_d(1),_s(1)],       "Deal 1 dmg. Gain 1 shield."),
    _card("I021","Blizzard Seed",    I,1,[_d(2)],              "Deal 2 damage."),
    _card("I022","Frost Needle",     I,1,[_d(2)],              "Deal 2 damage."),
    _card("I023","Winter Breath",    I,1,[_d(1),_st(1)],      "Deal 1 dmg. Opp loses 1 mana."),
    _card("I024","Ice Chip",         I,1,[_d(1),_s(1)],       "Deal 1 dmg. Gain 1 shield."),
    _card("I025","Crisp Air",        I,1,[_dr(1),_s(1)],      "Draw 1 card. Gain 1 shield."),
    _card("I026","Frost Veil",       I,1,[_s(4)],              "Gain 4 shield."),
    _card("I027","Cold Prick",       I,1,[_d(1)],              "Deal 1 damage."),
    _card("I028","Snow Drift",       I,1,[_s(2),_dr(1)],      "Gain 2 shield. Draw 1 card."),
    _card("I029","Glacier Tap",      I,1,[_d(2)],              "Deal 2 damage."),
    _card("I030","Ice Mist",         I,1,[_d(1),_s(1)],       "Deal 1 dmg. Gain 1 shield."),
    _card("I031","Frozen Tear",      I,1,[_d(2)],              "Deal 2 damage."),
    _card("I032","Chill Dart",       I,1,[_d(2)],              "Deal 2 damage."),
    _card("I033","Cold Light",       I,1,[_dr(1)],             "Draw 1 card."),
    _card("I034","Permafrost Touch", I,1,[_d(1),_s(2)],       "Deal 1 dmg. Gain 2 shield."),
    _card("I035","Hailstone",        I,1,[_d(2)],              "Deal 2 damage."),
    # ── 2-cost (35) ───────────────────────────────────────────────────────────
    _card("I036","Blizzard Strike",  I,2,[_d(3),_s(1)],       "Deal 3 dmg. Gain 1 shield."),
    _card("I037","Ice Lance",        I,2,[_d(4)],              "Deal 4 damage."),
    _card("I038","Frost Nova",       I,2,[_d(3),_fr(1)],      "Deal 3 dmg. Freeze opponent 1 turn."),
    _card("I039","Glacial Smash",    I,2,[_d(4)],              "Deal 4 damage."),
    _card("I040","Winter's Bite",    I,2,[_d(3),_s(2)],       "Deal 3 dmg. Gain 2 shield."),
    _card("I041","Ice Block",        I,2,[_s(6)],              "Gain 6 shield."),
    _card("I042","Cryo Bolt",        I,2,[_d(4)],              "Deal 4 damage."),
    _card("I043","Avalanche Chip",   I,2,[_d(3),_st(1)],      "Deal 3 dmg. Opp loses 1 mana."),
    _card("I044","Polar Slash",      I,2,[_d(4)],              "Deal 4 damage."),
    _card("I045","Ice Spear",        I,2,[_d(3),_s(1)],       "Deal 3 dmg. Gain 1 shield."),
    _card("I046","Blizzard Shard",   I,2,[_d(3),_dr(1)],      "Deal 3 dmg. Draw 1 card."),
    _card("I047","Frost Surge",      I,2,[_d(4)],              "Deal 4 damage."),
    _card("I048","Glacial Pulse",    I,2,[_d(3),_s(2)],       "Deal 3 dmg. Gain 2 shield."),
    _card("I049","Snow Cannon",      I,2,[_d(4)],              "Deal 4 damage."),
    _card("I050","Cryo Shield",      I,2,[_s(5),_d(1)],       "Gain 5 shield. Deal 1 damage."),
    _card("I051","Ice Whip",         I,2,[_d(3),_fr(1)],      "Deal 3 dmg. Freeze opponent 1 turn."),
    _card("I052","Frost Beam",       I,2,[_d(4)],              "Deal 4 damage."),
    _card("I053","Blizzard Touch",   I,2,[_d(3),_do(1)],      "Deal 3 dmg. Opponent discards 1."),
    _card("I054","Winter Spear",     I,2,[_d(3)],              "Deal 3 damage."),
    _card("I055","Icewall",          I,2,[_s(5),_dr(1)],      "Gain 5 shield. Draw 1 card."),
    _card("I056","Glacier Strike",   I,2,[_d(4)],              "Deal 4 damage."),
    _card("I057","Cryo Wave",        I,2,[_d(3),_st(1)],      "Deal 3 dmg. Opp loses 1 mana."),
    _card("I058","Frost Fang",       I,2,[_d(3),_s(2)],       "Deal 3 dmg. Gain 2 shield."),
    _card("I059","Ice Bomb",         I,2,[_d(3)],              "Deal 3 damage."),
    _card("I060","Frozen Bolt",      I,2,[_d(4)],              "Deal 4 damage."),
    _card("I061","Snow Crush",       I,2,[_d(3),_s(1)],       "Deal 3 dmg. Gain 1 shield."),
    _card("I062","Blizzard Burst",   I,2,[_d(4)],              "Deal 4 damage."),
    _card("I063","Cryogenic Blast",  I,2,[_d(3),_fr(1)],      "Deal 3 dmg. Freeze opponent 1 turn."),
    _card("I064","Ice Surge",        I,2,[_d(3),_dr(1)],      "Deal 3 dmg. Draw 1 card."),
    _card("I065","Polar Wave",       I,2,[_d(3),_st(1)],      "Deal 3 dmg. Opp loses 1 mana."),
    _card("I066","Frost Crush",      I,2,[_d(4)],              "Deal 4 damage."),
    _card("I067","Winter Rain",      I,2,[_d(3),_h(1)],       "Deal 3 dmg. Heal 1."),
    _card("I068","Icicle Barrage",   I,2,[_d(2),_d(2)],       "Deal 2 damage twice."),
    _card("I069","Cryo Pulse",       I,2,[_d(3),_s(1)],       "Deal 3 dmg. Gain 1 shield."),
    _card("I070","Glacier Wall",     I,2,[_s(4),_dr(1)],      "Gain 4 shield. Draw 1 card."),
    # ── 3-cost (20) ───────────────────────────────────────────────────────────
    _card("I071","Absolute Zero",    I,3,[_fr(2),_d(3)],      "Freeze 2 turns. Deal 3 damage."),
    _card("I072","Blizzard Tempest", I,3,[_d(6),_s(2)],       "Deal 6 dmg. Gain 2 shield."),
    _card("I073","Ice Age",          I,3,[_d(5),_fr(1),_s(2)],"Deal 5 dmg. Freeze 1 turn. Gain 2 shield."),
    _card("I074","Glacial Collapse", I,3,[_d(6)],              "Deal 6 damage."),
    _card("I075","Winter Storm",     I,3,[_d(5),_st(2)],      "Deal 5 dmg. Opp loses 2 mana."),
    _card("I076","Polar Vortex",     I,3,[_d(5),_dr(2)],      "Deal 5 dmg. Draw 2 cards."),
    _card("I077","Permafrost",       I,3,[_s(8),_d(1)],       "Gain 8 shield. Deal 1 damage."),
    _card("I078","Crystal Avalanche",I,3,[_d(5),_s(3)],       "Deal 5 dmg. Gain 3 shield."),
    _card("I079","Deep Freeze",      I,3,[_fr(2),_d(2)],      "Freeze 2 turns. Deal 2 damage."),
    _card("I080","Frostfall",        I,3,[_d(5),_do(2)],      "Deal 5 dmg. Opponent discards 2."),
    _card("I081","Cryo Surge",       I,3,[_d(6),_s(1)],       "Deal 6 dmg. Gain 1 shield."),
    _card("I082","Glacial Tsunami",  I,3,[_d(5),_h(2)],       "Deal 5 dmg. Heal 2."),
    _card("I083","Snow Emperor",     I,3,[_d(5),_dr(2)],      "Deal 5 dmg. Draw 2 cards."),
    _card("I084","Blizzard of Ages", I,3,[_d(5),_st(2)],      "Deal 5 dmg. Opp loses 2 mana."),
    _card("I085","Frozen Vortex",    I,3,[_d(5),_fr(1),_st(1)],"Deal 5 dmg. Freeze 1 turn. Opp -1 mana."),
    _card("I086","Ice God's Touch",  I,3,[_d(4),_s(4),_h(1)], "Deal 4 dmg. Gain 4 shield. Heal 1."),
    _card("I087","Winter Emperor",   I,3,[_d(6),_s(2)],       "Deal 6 dmg. Gain 2 shield."),
    _card("I088","Arctic Convergence",I,3,[_d(5),_dr(1),_s(2)],"Deal 5 dmg. Draw 1. Gain 2 shield."),
    _card("I089","Cryogenic Surge",  I,3,[_d(6)],              "Deal 6 damage."),
    _card("I090","Glacial Emperor",  I,3,[_d(5),_fr(1),_h(2)], "Deal 5 dmg. Freeze 1 turn. Heal 2."),
    # ── 4-cost (7) ────────────────────────────────────────────────────────────
    _card("I091","Absolute Freeze",  I,4,[_fr(3),_d(4)],      "Freeze 3 turns. Deal 4 damage."),
    _card("I092","Glacier God",      I,4,[_d(8),_s(3)],       "Deal 8 dmg. Gain 3 shield."),
    _card("I093","Arctic Devastation",I,4,[_d(7),_st(2),_s(2)],"Deal 7 dmg. Opp -2 mana. Gain 2 shield."),
    _card("I094","Permafrost Kingdom",I,4,[_s(10),_d(2)],     "Gain 10 shield. Deal 2 damage."),
    _card("I095","Winter's End",     I,4,[_d(7),_h(3)],       "Deal 7 dmg. Heal 3."),
    _card("I096","Cryo Apocalypse",  I,4,[_d(8),_fr(1)],      "Deal 8 dmg. Freeze 1 turn."),
    _card("I097","Ice Age Returns",  I,4,[_d(7),_dr(2),_st(2)],"Deal 7 dmg. Draw 2. Opp -2 mana."),
    # ── 5-cost (3) ────────────────────────────────────────────────────────────
    _card("I098","Eternal Winter",   I,5,[_d(10),_fr(2)],     "Deal 10 dmg. Freeze 2 turns."),
    _card("I099","Glacial Singularity",I,5,[_d(9),_s(5)],     "Deal 9 dmg. Gain 5 shield."),
    _card("I100","Primordial Ice",   I,5,[_d(8),_fr(2),_st(3)],"Deal 8 dmg. Freeze 2 turns. Opp -3 mana."),
]

# ══════════════════════════════════════════════════════════════════════════════
# LIGHTNING CARDS (100) — speed, draw, stun, energize
# ══════════════════════════════════════════════════════════════════════════════
LIGHTNING_CARDS = [
    # ── 1-cost (30) ───────────────────────────────────────────────────────────
    _card("L001","Spark",            L,1,[_d(2)],              "Deal 2 damage."),
    _card("L002","Static Shock",     L,1,[_d(1),_dr(1)],      "Deal 1 dmg. Draw 1 card."),
    _card("L003","Thunder Snap",     L,1,[_d(2)],              "Deal 2 damage."),
    _card("L004","Quick Bolt",       L,1,[_d(2)],              "Deal 2 damage."),
    _card("L005","Jolt",             L,1,[_d(1),_st(1)],      "Deal 1 dmg. Opp loses 1 mana."),
    _card("L006","Lightning Step",   L,1,[_d(2)],              "Deal 2 damage."),
    _card("L007","Static Pulse",     L,1,[_d(1),_dr(1)],      "Deal 1 dmg. Draw 1 card."),
    _card("L008","Shock Touch",      L,1,[_d(2)],              "Deal 2 damage."),
    _card("L009","Volt Snap",        L,1,[_d(2)],              "Deal 2 damage."),
    _card("L010","Thunder Tap",      L,1,[_d(1),_st(1)],      "Deal 1 dmg. Opp loses 1 mana."),
    _card("L011","Quick Arc",        L,1,[_d(2)],              "Deal 2 damage."),
    _card("L012","Spark Dance",      L,1,[_d(1),_dr(1)],      "Deal 1 dmg. Draw 1 card."),
    _card("L013","Static Flare",     L,1,[_d(2)],              "Deal 2 damage."),
    _card("L014","Thunder Jolt",     L,1,[_d(2)],              "Deal 2 damage."),
    _card("L015","Voltage Tap",      L,1,[_d(1),_dr(1)],      "Deal 1 dmg. Draw 1 card."),
    _card("L016","Storm Seed",       L,1,[_d(2)],              "Deal 2 damage."),
    _card("L017","Arc Flash",        L,1,[_d(2)],              "Deal 2 damage."),
    _card("L018","Electric Touch",   L,1,[_d(1),_en(1)],      "Deal 1 dmg. Gain 1 mana this turn."),
    _card("L019","Thunderclap",      L,1,[_d(2)],              "Deal 2 damage."),
    _card("L020","Shock Pulse",      L,1,[_d(1),_st(1)],      "Deal 1 dmg. Opp loses 1 mana."),
    _card("L021","Lightning Tap",    L,1,[_d(2)],              "Deal 2 damage."),
    _card("L022","Static Zap",       L,1,[_d(2)],              "Deal 2 damage."),
    _card("L023","Volt Pierce",      L,1,[_d(2)],              "Deal 2 damage."),
    _card("L024","Thunder Bite",     L,1,[_d(1),_dr(1)],      "Deal 1 dmg. Draw 1 card."),
    _card("L025","Arc Snap",         L,1,[_d(2)],              "Deal 2 damage."),
    _card("L026","Electric Seed",    L,1,[_dr(2)],             "Draw 2 cards."),
    _card("L027","Spark Web",        L,1,[_d(1),_st(1)],      "Deal 1 dmg. Opp loses 1 mana."),
    _card("L028","Storm Touch",      L,1,[_d(2)],              "Deal 2 damage."),
    _card("L029","Bolt Flick",       L,1,[_d(2)],              "Deal 2 damage."),
    _card("L030","Volt Seed",        L,1,[_dr(1),_d(1)],      "Draw 1 card. Deal 1 damage."),
    # ── 2-cost (35) ───────────────────────────────────────────────────────────
    _card("L031","Chain Lightning",  L,2,[_d(2),_d(2)],       "Deal 2 damage twice."),
    _card("L032","Thunder Strike",   L,2,[_d(4)],              "Deal 4 damage."),
    _card("L033","Volt Surge",       L,2,[_d(3),_dr(1)],      "Deal 3 dmg. Draw 1 card."),
    _card("L034","Arc Blade",        L,2,[_d(4)],              "Deal 4 damage."),
    _card("L035","Static Storm",     L,2,[_d(3),_st(1)],      "Deal 3 dmg. Opp loses 1 mana."),
    _card("L036","Lightning Spear",  L,2,[_d(4)],              "Deal 4 damage."),
    _card("L037","Electric Burst",   L,2,[_d(3),_en(1)],      "Deal 3 dmg. Gain 1 mana this turn."),
    _card("L038","Thunder Crash",    L,2,[_d(4)],              "Deal 4 damage."),
    _card("L039","Volt Slash",       L,2,[_d(3),_dr(1)],      "Deal 3 dmg. Draw 1 card."),
    _card("L040","Storm Pulse",      L,2,[_d(3),_st(1)],      "Deal 3 dmg. Opp loses 1 mana."),
    _card("L041","Arc Wave",         L,2,[_d(4)],              "Deal 4 damage."),
    _card("L042","Lightning Rush",   L,2,[_d(3),_en(1)],      "Deal 3 dmg. Gain 1 mana."),
    _card("L043","Static Beam",      L,2,[_d(4)],              "Deal 4 damage."),
    _card("L044","Bolt Cannon",      L,2,[_d(3),_dr(1)],      "Deal 3 dmg. Draw 1 card."),
    _card("L045","Thunder Blade",    L,2,[_d(4)],              "Deal 4 damage."),
    _card("L046","Volt Chain",       L,2,[_d(2),_d(2),_dr(1)],"Deal 2 damage twice. Draw 1 card."),
    _card("L047","Stormbreaker",     L,2,[_d(4),_st(1)],      "Deal 4 dmg. Opp loses 1 mana."),
    _card("L048","Arc Surge",        L,2,[_d(3),_dr(2)],      "Deal 3 dmg. Draw 2 cards."),
    _card("L049","Electric Fang",    L,2,[_d(3)],              "Deal 3 damage."),
    _card("L050","Thunder Wave",     L,2,[_d(3),_st(1)],      "Deal 3 dmg. Opp loses 1 mana."),
    _card("L051","Volt Burst",       L,2,[_d(4)],              "Deal 4 damage."),
    _card("L052","Storm Slash",      L,2,[_d(3),_en(1)],      "Deal 3 dmg. Gain 1 mana."),
    _card("L053","Lightning Dance",  L,2,[_d(3),_dr(1)],      "Deal 3 dmg. Draw 1 card."),
    _card("L054","Arc Cannon",       L,2,[_d(4)],              "Deal 4 damage."),
    _card("L055","Electric Strike",  L,2,[_d(3)],              "Deal 3 damage."),
    _card("L056","Thunder Surge",    L,2,[_d(3),_en(2)],      "Deal 3 dmg. Gain 2 mana this turn."),
    _card("L057","Volt Rush",        L,2,[_d(3),_st(1)],      "Deal 3 dmg. Opp loses 1 mana."),
    _card("L058","Storm Arc",        L,2,[_d(4)],              "Deal 4 damage."),
    _card("L059","Lightning Beam",   L,2,[_d(3),_dr(1)],      "Deal 3 dmg. Draw 1 card."),
    _card("L060","Arc Tempest",      L,2,[_d(3),_st(1),_dr(1)],"Deal 3 dmg. Opp -1 mana. Draw 1."),
    _card("L061","Static Wave",      L,2,[_d(3)],              "Deal 3 damage."),
    _card("L062","Thunderbolt",      L,2,[_d(4)],              "Deal 4 damage."),
    _card("L063","Electric Wave",    L,2,[_d(3),_dr(1)],      "Deal 3 dmg. Draw 1 card."),
    _card("L064","Volt Tempest",     L,2,[_d(4)],              "Deal 4 damage."),
    _card("L065","Storm Strike",     L,2,[_d(4)],              "Deal 4 damage."),
    # ── 3-cost (25) ───────────────────────────────────────────────────────────
    _card("L066","Lightning Emperor",L,3,[_d(6),_dr(2)],      "Deal 6 dmg. Draw 2 cards."),
    _card("L067","Thunder God's Strike",L,3,[_d(7)],           "Deal 7 damage."),
    _card("L068","Storm Convergence",L,3,[_d(5),_dr(3)],      "Deal 5 dmg. Draw 3 cards."),
    _card("L069","Volt Tsunami",     L,3,[_d(6),_st(2)],      "Deal 6 dmg. Opp loses 2 mana."),
    _card("L070","Arc Collapse",     L,3,[_d(5),_d(3)],       "Deal 5 damage then 3 more."),
    _card("L071","Thunder Tempest",  L,3,[_d(6),_dr(1),_st(1)],"Deal 6 dmg. Draw 1. Opp -1 mana."),
    _card("L072","Static Apocalypse",L,3,[_d(5),_st(2),_dr(1)],"Deal 5 dmg. Opp -2 mana. Draw 1."),
    _card("L073","Electric Surge",   L,3,[_d(5),_en(2)],      "Deal 5 dmg. Gain 2 mana."),
    _card("L074","Stormbreaker Alpha",L,3,[_d(6),_dr(1)],     "Deal 6 dmg. Draw 1 card."),
    _card("L075","Volt Cascade",     L,3,[_d(5),_dr(2)],      "Deal 5 dmg. Draw 2 cards."),
    _card("L076","Arc God",          L,3,[_d(6),_st(1)],      "Deal 6 dmg. Opp loses 1 mana."),
    _card("L077","Thunder Wave Alpha",L,3,[_d(5),_dr(2)],     "Deal 5 dmg. Draw 2 cards."),
    _card("L078","Lightning Cascade",L,3,[_d(5),_en(2)],      "Deal 5 dmg. Gain 2 mana."),
    _card("L079","Storm God's Touch",L,3,[_d(5),_h(2),_dr(1)],"Deal 5 dmg. Heal 2. Draw 1."),
    _card("L080","Bolt Surge",       L,3,[_d(6)],              "Deal 6 damage."),
    _card("L081","Electric Emperor", L,3,[_d(5),_dr(2),_st(1)],"Deal 5 dmg. Draw 2. Opp -1 mana."),
    _card("L082","Volt God",         L,3,[_d(6),_en(1)],      "Deal 6 dmg. Gain 1 mana."),
    _card("L083","Arc Tsunami",      L,3,[_d(5),_d(2),_dr(1)],"Deal 5 then 2 damage. Draw 1."),
    _card("L084","Thunder Cascade",  L,3,[_d(6)],              "Deal 6 damage."),
    _card("L085","Storm Emperor",    L,3,[_d(5),_dr(3)],      "Deal 5 dmg. Draw 3 cards."),
    _card("L086","Lightning God",    L,3,[_d(6),_st(2)],      "Deal 6 dmg. Opp loses 2 mana."),
    _card("L087","Static Tsunami",   L,3,[_d(5),_dr(2)],      "Deal 5 dmg. Draw 2 cards."),
    _card("L088","Volt Emperor",     L,3,[_d(6),_dr(1)],      "Deal 6 dmg. Draw 1 card."),
    _card("L089","Arc Emperor",      L,3,[_d(5),_st(2),_dr(1)],"Deal 5 dmg. Opp -2 mana. Draw 1."),
    _card("L090","Thunder God",      L,3,[_d(6),_en(2)],      "Deal 6 dmg. Gain 2 mana."),
    # ── 4-cost (7) ────────────────────────────────────────────────────────────
    _card("L091","Heaven's Lightning",L,4,[_d(8),_dr(2)],     "Deal 8 dmg. Draw 2 cards."),
    _card("L092","Thunder God's Wrath",L,4,[_d(8),_st(2)],    "Deal 8 dmg. Opp loses 2 mana."),
    _card("L093","Arc Annihilation", L,4,[_d(7),_dr(3)],      "Deal 7 dmg. Draw 3 cards."),
    _card("L094","Storm God",        L,4,[_d(7),_en(3)],      "Deal 7 dmg. Gain 3 mana this turn."),
    _card("L095","Volt God's Fury",  L,4,[_d(8),_st(3)],      "Deal 8 dmg. Opp loses 3 mana."),
    _card("L096","Lightning King",   L,4,[_d(7),_dr(2),_st(1)],"Deal 7 dmg. Draw 2. Opp -1 mana."),
    _card("L097","Static Singularity",L,4,[_d(6),_dr(2),_st(2)],"Deal 6 dmg. Draw 2. Opp -2 mana."),
    # ── 5-cost (3) ────────────────────────────────────────────────────────────
    _card("L098","End of the Storm", L,5,[_d(10),_dr(2)],     "Deal 10 dmg. Draw 2 cards."),
    _card("L099","Thor's Final Strike",L,5,[_d(9),_st(3),_dr(1)],"Deal 9 dmg. Opp -3 mana. Draw 1."),
    _card("L100","Primordial Lightning",L,5,[_d(9),_en(3),_dr(2)],"Deal 9 dmg. Gain 3 mana. Draw 2."),
]

# ── Master lookup ──────────────────────────────────────────────────────────────
ALL_CARDS: dict[str, dict] = {
    c["id"]: c for c in FIRE_CARDS + ICE_CARDS + LIGHTNING_CARDS
}

BY_ELEMENT: dict[str, list] = {
    "fire":      FIRE_CARDS,
    "ice":       ICE_CARDS,
    "lightning": LIGHTNING_CARDS,
}
